version: "3"
services:
  currency-exchange-service:
    image: currency-exchange-service
    restart: always
    build: .
    ports:
      - 8000:8000
    environment: 
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      
      
        